apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    name: nginx-service
    environment: DEV
spec:
  selector:
  # you should provide pod labels here
    app: nginx
  ports:
  - name: http-port
    protocol: TCP
    # service port
    port: {{ .Values.service.port }}
    # pod port
    targetPort: 80